version: "3"

services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - $PWD/data:/data/db
    networks:
      - ntwrk
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  api:
    container_name: api_container
    image: api_container
    ports:
      - "8100:8080"
    networks:
      - ntwrk

networks:
  ntwrk:
