version: '2'
services:

  postgresql_db_2:
    image: postgres:11.15
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - psql_backup:/home/Desktop/docker/backup

  

volumes:
  psql_backup:
    driver: local



