version: '3'
services:
  db:
    image: postgres
    networks:
      - gpt_net
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
  web:
    image: nginx
    networks:
      - gpt_net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  app:
    build: .
    networks:
      - gpt_net
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
networks:
  gpt_net:
    driver: bridge
