version: '3'

services:
  postgres_database:
    container_name: postgres_database
    image: postgres:13.6
    ports:
      - 5500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /home/obukowski/Desktop/backups/postgres_backup:/var/lib/postgresql/data
    networks:
      - network

  ubuntu_host:
    container_name: ubuntu_host
    image: ubuntu
    restart: on-failure
#    command: ["sleep","infinity"]
    networks:
      - network

  jenkins_v2:
    container_name: jenkins_v2
    image: jenkins/jenkins
    ports:
      - 8100:8080
    volumes:
      - /home/obukowski/Desktop/backups/jenkins_home:/var/jenkins_home
    networks:
      - network


networks:
  network: